qsp:
  serverName: "Local dev server"
  serverDescription: "Local execution of the signaling server"

server:
  port: 7080

database:
  postgresql:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "pgpass"
    database: "postgres"


agent:
  hmac:
    keyLength: 64

logging.level:
  fr.f4fez: TRACE