qsp:
  serverName: "Local dev server"
  serverDescription: "Local execution of the signaling server"

server:
  port: 7080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgpass
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.10.40:81/auth
  output.ansi.enabled: ALWAYS
agent:
  hmac:
    keyLength: 64

logging.level:
  root: INFO