qsp:
  serverName: "Local dev server"
  serverDescription: "Local execution of the signaling server"

server:
  port: 7080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgpass

agent:
  hmac:
    keyLength: 64

logging.level:
  fr.f4fez: TRACE