name: Signaling server CI

on:
  push:
    branches:
      - master
      - ciTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Validate Gradle wrapper'
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: bootJar
      - name: Upload build JAR
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Download gradle build result
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - run: pwd
      - run: ls build/libs/
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: f4fez/qrp-signaling-server:latest
          context: .
          file: .package/Dockerfile