name: Signaling server CI

on:
  push:
    branches:
      - main
      - ciTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Upload build JAR
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Download gradle build result
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - run: pwd
      - run: ls build/libs/
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: f4fez/qrp-signaling-server:latest
          context: .
          file: .package/Dockerfile